name: Push major tag

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  tag-major:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Check and create major tag
        env:
          REF_NAME: ${{ github.ref_name }}
        run: |
          semver="v[[:digit:]]+[.][[:digit:]]"
          if [[ "$REF_NAME" =~ ${semver} ]]; then
            if [[ "$REF_NAME" == *"-rc"* ]]; then
              echo "Ignoring rc version"
            else
              echo "Pushing ${major}"
              major=$(echo "$REF_NAME" | cut -d '.' -f 1)
              git tag -f "${major}"
              git push -f origin "${major}"
            fi
          fi
